main/qt6-qtwebengine: revert disable jumbo build
Fails with a different error:

src/3rdparty/chromium/media/filters/ffmpeg_glue.cc:233:13: error: use of undeclared identifier 'INFO'

This reverts commit bc824e79af3ff2b262adf73abec3a1e9abd636c7.